schema_version: 20180708
name: factorial
version: 0.0.25
runtime: go
build_image: fnproject/go:1.20-dev
run_image: fnproject/go:1.20
entrypoint: ./func
triggers:
- name: factorial
  type: http
  source: /factorial
